apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch-app
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
          - name: discovery.type
            value: single-node
        volumeMounts:
          - name: elasticsearch-pv
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-pv
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
