apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-app
  ports:
  - name: port9200
    port: 9200
  - name: port9300
    port: 9300
