apiVersion: v1
data:
  Corefile: |-
    . {
        hosts {
            # 192.168.0.101 minio.local
            # 192.168.0.101 juice-shop.local
            # 192.168.0.101 kibana.local
            # 192.168.0.101 send.local
            100.96.1.34 minio.local
            100.96.1.34 juice-shop.local
            100.96.1.34 kibana.local
            100.96.1.34 send.local
            fallthrough
        }
        forward . 8.8.8.8
        reload
    }
kind: ConfigMap
metadata:
  name: coredns-configmap
