apiVersion: v1
kind: Service
metadata:
  name: send-service
spec:
  type: ClusterIP
  selector:
    app: send-app
  ports:
  - protocol: "TCP"
    port: 1443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-app
  template:
    metadata:
      labels:
        app: send-app
    spec:
      containers:
        - name: send-container
          image: ghcr.io/moritalous/send:latest
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: FXA_REQUIRED
              value: "false"
            # - name: FILE_DIR
            #   value: /tmp/send
            # - name: BASE_URL
            #   value: http://raspberrypi.local:31443
            # - name: NODE_ENV
            #   value: development
            # - name: L10N_DEV
            #   value: "true"
            # - name: FXA_CLIENT_ID
            #   value: fced6b5e3f4c66b9
