---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  53: "default/coredns-service:53"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-udp-microk8s-conf
  namespace: ingress
data:
  53: "default/coredns-service:53"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller-2
  namespace: ingress
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s-controller-2
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s-controller-2
    spec:
      containers:
      - name: nginx-ingress-microk8s
        args:
        - /nginx-ingress-controller
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp-microk8s-conf
        - --udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp-microk8s-conf
        - --publish-status-address=127.0.0.1
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm64:0.32.0
        ports:
        - containerPort: 80
        - containerPort: 443
        - name: proxied-tcp-53
          containerPort: 53
          hostPort: 53
          protocol: TCP
        - name: proxied-udp-53
          containerPort: 53
          hostPort: 53
          protocol: UDP