apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: minio-pvc
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-10-28T08-16-50Z-arm64
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        args:
        - server
        - /storage
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "miniominio"
        ports:
        - containerPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: minio-storage # must match the volume name, above
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30090
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: manual
    selector:
      matchLabels:
        app: minio
    resources:
      requests:
        storage: 30Gi