apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    app.kubernetes.io/name: influxdb
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/influxdb"
