apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  selector:
    matchLabels:
      app: kibana-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana-app
    spec:
      containers:
      - name: kibana
        image: ghcr.io/moritalous/ghcr/kibana-arm64:7.9.1
        ports:
        - containerPort: 5601
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-service:9200
